### ISSUE TITLE
Ideas: Pi Shutdown and Double Click Input

### ISSUE THREAD

**Issue by jordankooyman** [LuxuSam/PhysicalButton#22]
It would be really cool if one of the button actions could be to safe shut down the Pi. I have tried a few other plugins, but they do not have the configurability I have seen here. It would also be cool if you could implement a double click input, so that if a button gets bumped, it won't necessarily trigger a function, particularly the Pi shut down.

**Comment by LuxuSam** [comment]
Good idea, I had already thought about adding the possibility to run scripts or commands to the executable activities, that would then also include to shut the Pi down :D

Regarding your suggestion for the double click, _Hold Time_ in the button configuration is meant to keep the button from accidentally being triggered. If for instance you set the hold time to 1 second, the button has to be pressed 1 second in order to execute the activities, else the button press will be ignored.
I thought this was the easiest way to ensure that a button is only  triggered when you want it to.

**Comment by LuxuSam** [comment]
@jordankooyman
With the new release you can add a system command for instance to shut down the pi :) Just add a system action and copy the shutdown command from _Settings > Server > Shutdown system_ and paste it in the input field. :D

Cheers,
Sam

**Comment by jordankooyman** [comment]
Thank you very much! I hope this will work better than what I have tried in the past.

**Comment by electronicm** [comment]
@jordankooyman Take a look at [dtoverlay:gpio-shutdown](https://www.google.com/search?q=dtoverlay:gpio-shutdown).
It is the native way to shutdown the Pi via gpio.
If you use the standard pin GPIO3, the PI can also be started with the button
